# Generated by Django 3.0.5 on 2021-12-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.TextField(null=True)),
                ('p1n', models.CharField(max_length=50)),
                ('p1i', models.CharField(max_length=100)),
                ('p2n', models.CharField(max_length=50)),
                ('p2i', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
